steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['clean','package']
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/dataset-rbc/dataset-rb', '--build-arg=JAR_FILE=target/dataset-1.0-SNAPSHOT.jar', '.' ]
